name: Testing

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test

    - name: Lint with ESLint
      run: npm run lint
